### ISSUE TITLE
Random Reboot with SW_BINARIES_FOR_XPERIA_ANDROID_9.0_2.3.2_V7_YOSHINO.ZIP

### ISSUE THREAD

**Issue by wyzco** [sonyxperiadev/device-sony-yoshino#129]
I have attached the dmes, event, logcat and modem logs of my device
between the time 13:04:39.712 to 13:04:40.737 there were calls which triggered a restart of the device (XZ1 Compact).

[dmesg.log](https://github.com/sonyxperiadev/device-sony-yoshino/files/3045469/dmesg.log)
[event.log](https://github.com/sonyxperiadev/device-sony-yoshino/files/3045470/event.log)
[logcat.log](https://github.com/sonyxperiadev/device-sony-yoshino/files/3045471/logcat.log)
[modem.log](https://github.com/sonyxperiadev/device-sony-yoshino/files/3045472/modem.log)

**Comment by bartcubbins** [comment]
Please use bug tracker
https://github.com/sonyxperiadev/bug_tracker

**Comment by jerpelea** [comment]
please use the bugtracker
