### ISSUE TITLE
Video camera framerate low on Oreo

### ISSUE THREAD

**Issue by jlivings** [sonyxperiadev/device-sony-yoshino#50]
The XZ1 (poplar) video camera is capable of 2160p@30fps, 1080p@30/60fps, 720p@960fps (slo-mo). Currently, if we try to use it at 1080p@60, as was enabled briefly by commit d4ea034, the camera fails to start recording and an error is logged saying the camera is only capable of 15/20/24/30fps. The 2160p resolution is also not available.

**Comment by jerpelea** [comment]
in the AOSP viseo recording supports 30fps

**Comment by jerpelea** [comment]
maximum resolution is 1920x1080
