### ISSUE TITLE
Wi-Fi not work and bluetooth keep crash

### ISSUE THREAD

**Issue by DevriesL** [sonyxperiadev/device-sony-yoshino#59]

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker to report issues

**Comment by jerpelea** [comment]
please use the latest binaries v6 
https://developer.sony.com/file/download/software-binaries-for-aosp-oreo-android-8-0-kernel-4-4-yoshino/

**Comment by DevriesL** [comment]
Hello @jerpelea , I think it's a hyperlink error, when I click "2017-11-02: Update of AOSP Oreo binaries (Android 8.0 – Kernel 4.4) for Xperia XZ Premium, Xperia XZ1 and Xperia XZ1 Compact", the download link is v05.

**Comment by jerpelea** [comment]
i just downloaded v6 from the link i shared

**Comment by DevriesL** [comment]
@jerpelea I mean it is a website link error, you can try to download from: https://developer.sonymobile.com/open-devices/latest-updates/ 2017-11-02: Update of AOSP Oreo binaries (Android 8.0 – Kernel 4.4)

**Comment by jerpelea** [comment]
please use the new website https://developer.sony.com as i specified in the link
